layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: GNU
    web_url: http://www.gnu.org
    image_url: http://www.gnu.org/graphics/gnu-head-sm.jpg

  - name: Linux
  
  - name: Apache

  - name: PHP

  - name: MySQL

  - name: HTML5

  - name: CSS3
    web_url: https://github.com/topics/css
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png
    
  - name: Javascript
  
  - name: jQuery
